### ISSUE TITLE
HTML版の一部画像が表示されていない

### ISSUE THREAD

**Issue by ichigotake** [keiji/the-androidstudio-book#2]
http://keiji.github.io/the-androidstudio-book/

"Java for OS Xのインストール" の項目に画像が表示されていません。

PDF版やリポジトリ内の画像のファイル名は正しいように見えるので、Github Pages の更新忘れでしょうか。

以下、Github Pages で404エラーが出る画像です。s/jdk6/jdk7/ で画像が存在する事を確認しました。
- images/install_jdk/mac-jdk6-install1.png
- images/install_jdk/mac-jdk6-install2.png
- images/install_jdk/mac-jdk6-install3.png
- images/install_jdk/mac-jdk6-install4.png
- images/install_jdk/mac-jdk6-install5.png

**Comment by keiji** [comment]
修正しました。また何かあればReopenをお願いします。
